export const SET_BREADCRUMB = 'SET_BREADCRUMB';
export const CLEAR_BREADCRUMB = 'CLEAR_BREADCRUMB';
export const SET_ACTIVE_SIDEBAR_ITEM = 'SET_ACTIVE_SIDEBAR_ITEM';
export const CLEAR_ACTIVE_SIDEBAR_ITEM = 'CLEAR_ACTIVE_SIDEBAR_ITEM';

export const GET_ACCESS_TOKEN = 'GET_ACCESS_TOKEN';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const SET_TOKEN = 'SET_TOKEN';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const SET_STATUS = 'SET_STATUS';

export const PREPARE_REQUEST = 'PREPARE_REQUEST';
export const GET_RESOURCE = 'GET_RESOURCE';
export const ADD_REQUEST = 'ADD_REQUEST';
export const DELETE_REQUEST = 'DELETE_REQUEST';
export const ADD_RESPONSE = 'ADD_RESPONSE';
export const DELETE_RESPONSE = 'DELETE_RESPONSE';

export const FETCH_PERMISSIONS = 'FETCH_PERMISSIONS';
export const SET_PERMISSIONS = 'SET_PERMISSIONS';
export const GET_PERMISSIONS = 'GET_PERMISSIONS';