export const SET_BREADCRUMB = 'SET_BREADCRUMB';
export const CLEAR_BREADCRUMB = 'CLEAR_BREADCRUMB';
export const SET_ACTIVE_SIDEBAR_ITEM = 'SET_ACTIVE_SIDEBAR_ITEM';
export const CLEAR_ACTIVE_SIDEBAR_ITEM = 'CLEAR_ACTIVE_SIDEBAR_ITEM';