export const SET_BREADCRUMB = 'SET_BREADCRUMB';
export const CLEAR_BREADCRUMB = 'CLEAR_BREADCRUMB';
export const SET_ACTIVE_SIDEBAR_ITEM = 'SET_ACTIVE_SIDEBAR_ITEM';
export const CLEAR_ACTIVE_SIDEBAR_ITEM = 'CLEAR_ACTIVE_SIDEBAR_ITEM';

export const GET_ACCESS_TOKEN = 'GET_ACCESS_TOKEN';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const SET_TOKEN = 'SET_TOKEN';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const SET_STATUS = 'SET_STATUS';